### ISSUE TITLE
Code Quiz

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/code-quiz#1]
## Acceptance Criteria
- [x] timer starts and the user prevented with a question
- [x] after answering one question, the user is presented with another
- [x] 10 sec time decrement to clock if an incorrect answer is provided
- [x] All questions are answered or the timer reaches 0
- [x] the quiz is over
- [x] user enters initials and score is recorded

## To-do
- [x] resolve CSS reset
- [x] finish high scores page
- [x] format form on quiz summary page
- [x] remove pseudocode in script.js before deployment
